[#656] feat(library) Support Standalone Workflow Builder
krzema12/github-workflows-kt pull request #657
Opened 2023-01-30 14:09 UTC by mfwgenerics

This addresses issue #656:

* `sourceFile` and `targeFileName` arguments to `workflow` have both become nullable
* `sourceFile` is now optional and defaults to `null`
* Corresponding fields on Workout and WorkoutBuilder are made nullable too
* A slightly different preamble is generated when `sourceFile` is not present
* `addConsistencyCheck` now defaults to false if `sourceFile` is absent on both `toYaml` and `writeToFile`
* `gitRootDir` is now nullable
* `writeToFile` can be used without `sourceFile` as long as `targetFileName` and `gitRootDir` are still provided

2023-01-31 14:47 UTC, krzema12 requested changes

2023-01-31 14:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +    }
```suggestion
    val sourceFilePath = gitRootDir?.let {
        sourceFile?.relativeToAbsolute(it)?.invariantSeparatorsPathString
    }
```

2023-01-31 14:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +    /* preamble slightly differs on lines 1 and 2 when sourceFilePath is not available */
```suggestion
```

IMO not needed, it's visible in the code.

2023-01-31 14:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +        # If you want to modify the workflow, please change the Kotlin source and regenerate this YAML file.
I'm wondering if you, as an author of markout, would like to have a way to put something custom here. E.g. "If you want to modify this workflow, check 'markout' configuration". "please change the Kotlin source" doesn't look very informative for a newcomer.

2023-01-31 14:47 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StandaloneWorkflowTest.kt
> +    it("should allow toYaml without sourceFile") {
Let's have this test in library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt. I know this file is pretty large and I'm planning to refactor it, but I wouldn't like to have this inconsistency of having tests in various places.

2023-01-31 16:16 UTC, krzema12 commented
@mfwgenerics please don't force-push from now on, let's have fixup commits.

2023-02-01 04:21 UTC, mfwgenerics commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +    }
Good catch

2023-02-01 04:23 UTC, mfwgenerics commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +    /* preamble slightly differs on lines 1 and 2 when sourceFilePath is not available */
Rationale for this was that the difference on line 2 did not feel obvious at first glance. I've removed the comment :+1:

2023-02-01 04:27 UTC, mfwgenerics commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StandaloneWorkflowTest.kt
> +    it("should allow toYaml without sourceFile") {
I've moved both Standalone tests to IntegrationTest

2023-02-01 04:33 UTC, mfwgenerics commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +        # If you want to modify the workflow, please change the Kotlin source and regenerate this YAML file.
It would be good to be able to provide my own preamble through an argument to `toYaml()`. I could add that as part of this PR if you think it is within scope.

2023-02-01 06:33 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +        # If you want to modify the workflow, please change the Kotlin source and regenerate this YAML file.
Ok, let's add it in a follow-up PR.

2023-02-01 07:47 UTC, krzema12 approved these changes

2023-02-01 07:47 UTC, merged