docs: use new pymdown-extensions that is able to unindent snippets
krzema12/github-workflows-kt pull request #696
Opened 2023-02-24 17:19 UTC by Vampire

2023-02-24 18:30 UTC, krzema12 commented
That's really cool, thanks! I'll wait these 2 weeks, it's not that long to depend on a stable version

2023-02-24 21:05 UTC, krzema12 commented on docs/user-guide/compensating-librarys-missing-features.md
> ---8<-- "CompensatingLibrarysMissingFeaturesSnippets.kt:customArguments1"
Isn't camel case supported?

2023-02-24 22:02 UTC, Vampire commented on docs/user-guide/compensating-librarys-missing-features.md
> ---8<-- "CompensatingLibrarysMissingFeaturesSnippets.kt:customArguments1"
Up to 9.9 only uppercase, lowercase, and digits were allowed.
For such IDs I prefer kebab-case for readability.
9.10 also adds the possibility to use dashes and underscores.
If you prefer them in camel case, I'll take those changes out.

2023-02-25 09:58 UTC, krzema12 commented on docs/user-guide/compensating-librarys-missing-features.md
> ---8<-- "CompensatingLibrarysMissingFeaturesSnippets.kt:customArguments1"
I have no strong opinion regarding the casing itself, but I do my best to avoid unrelated changes. As a thought exercise, someone may find this commit/PR to learn how to fix the indent issue: they will think that

- another mkdocs plugin is needed (or just a new version while the needed feature is in beta release?)
- setting a flag in config is needed
- the new mkdocs plugin needs different casing for placeholder names

The first two seem to be the minimal subset of changes needed, so I'd be grateful if you could follow this approach :)

2023-02-25 13:08 UTC, Vampire commented on docs/user-guide/compensating-librarys-missing-features.md
> ---8<-- "CompensatingLibrarysMissingFeaturesSnippets.kt:customArguments1"
I would agree if the PR and commit message were "add unindenting", but it was "use new pymdown extensions" :-D
But sure, I split it into three commits now. :-)

2023-03-06 09:41 UTC, krzema12 commented on docs/requirements.txt
> +pymdown-extensions==9.10
Is this override needed? See

https://github.com/mkdocs/mkdocs/blob/56b235a8ad43f2300d17f87e6fa4de7a3d764397/pyproject.toml#L193

`pymdown-extensions` is in fact a transitive dependency coming with `mkdocs`. There's a version range defined in `mkdocs`. I tried it locally - works without this override.

2023-03-06 10:25 UTC, krzema12 requested changes
.

2023-03-06 12:15 UTC, Vampire commented on docs/requirements.txt
> +pymdown-extensions==9.10
Actually, the line you linked to is probably not the correct line.
At least `pipdeptree` says `mkdocs` has no dependency on `pymdown-extensions`, but `mkdocs-material` has, with version `required: >=9.9.1`.

Well, it's such a thing with ranges (which I generally dislike also in Java, at least without some additional locking and only publishing resolved versions).
`>= 9.9.1` means having 9.9.1 would also be ok, but with that it wouldn't work at at least 9.10 is necessary.
If you prefer to gamble and just hope that at least 9.10 is present, I can of course remove the override. :-)

Also, if you already have 9.9.1 or newer installed, `pip install -r docs/requirements.txt` will just say
> Requirement already satisfied: pymdown-extensions>=9.9.1 in d:\programme\python39\lib\site-packages (from mkdocs-material==9.1.1->-r docs/requirements.txt (line 3)) (9.10b2)

and not install a newer version.
In your test it only worked because you either had 9.10 already installed, or no version installed.

2023-03-06 12:57 UTC, krzema12 commented on docs/requirements.txt
> +pymdown-extensions==9.10
Ok, got it. If we wanted to be really strict about it, we should analyze where version ranges are used wherever we depend on some frature of a transitive dependency, and then lock the version in our lib. However I think it would be an overkill for now, let's leave it as is for now 😊

2023-03-06 12:57 UTC, merged